apiVersion: v1
kind: Service
metadata:
  name: app-pemula-service
spec:
  type: NodePort
  selector:
    app: web-pemula
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
