name: CI/CD Lokal ke Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: 1. Ambil Kode Terbaru dari Git
      uses: actions/checkout@v4

    - name: 2. Build Docker Image Secara Lokal
      run: |
        docker build -t hello-devops:latest .

    - name: 3. Muat Image Baru ke Minikube
      run: |
        minikube image load hello-devops:latest

    - name: 4. Deploy Ulang ke Kubernetes
      run: |
        minikube kubectl -- apply -f k8s/deployment.yaml
        minikube kubectl -- apply -f k8s/service.yaml
        
    - name: 5. Paksa Kubernetes Lakukan Rolling Update
      run: |
        minikube kubectl -- rollout restart deployment/app-pemula-deployment
